from enum import Enum


class UserTypes(str, Enum):
    SUPERADMIN = "SUPERADMIN"
    ADMIN = "ADMIN"
    BUSINESS_OWNER = "BUSINESS_OWNER"
    BUSINESS_EMPLOYEE = "BUSINESS_EMPLOYEE"
    CUSTOMER = "CUSTOMER"
    CALL_CENTRE_AGENT = "CALL_CENTRE_AGENT"
