"""Set users is_active to True as default

Revision ID: 0197809287c7
Revises: 7ccf1b18fc57
Create Date: 2023-03-11 10:37:47.215759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0197809287c7"
down_revision = "7ccf1b18fc57"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
