"""Drop back_populates in favour of back_ref

Revision ID: 0f3baa74c56e
Revises: 91728cc9c074
Create Date: 2023-03-04 15:12:36.298224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0f3baa74c56e"
down_revision = "91728cc9c074"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
