"""Add country relationship to BusinessPartner model

Revision ID: 187e5d694a81
Revises: b63bbb5b2a5f
Create Date: 2023-03-14 19:27:48.583549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "187e5d694a81"
down_revision = "b63bbb5b2a5f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "businesspartner", sa.Column("country_id", sa.String(), nullable=True)
    )
    op.create_foreign_key(None, "businesspartner", "country", ["country_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "businesspartner", type_="foreignkey")
    op.drop_column("businesspartner", "country_id")
    # ### end Alembic commands ###
