"""Modify UserRole model

Revision ID: 2d33649a39e0
Revises: 66e591c6c17d
Create Date: 2023-03-08 18:03:46.210815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2d33649a39e0"
down_revision = "66e591c6c17d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("userrole_user_id_key", "userrole", type_="unique")
    op.drop_constraint("userrole_role_id_fkey", "userrole", type_="foreignkey")
    op.drop_constraint("userrole_user_id_fkey", "userrole", type_="foreignkey")
    op.create_foreign_key(None, "userrole", "role", ["role_id"], ["id"])
    op.create_foreign_key(None, "userrole", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "userrole", type_="foreignkey")
    op.drop_constraint(None, "userrole", type_="foreignkey")
    op.create_foreign_key(
        "userrole_user_id_fkey",
        "userrole",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "userrole_role_id_fkey",
        "userrole",
        "role",
        ["role_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_unique_constraint("userrole_user_id_key", "userrole", ["user_id"])
    # ### end Alembic commands ###
