"""Remove deleted column in BusinessPartner model

Revision ID: 32c68bd854b8
Revises: c965dfb7e3b2
Create Date: 2023-03-15 01:18:04.154120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "32c68bd854b8"
down_revision = "c965dfb7e3b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("businesspartner", "deleted")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "businesspartner",
        sa.Column("deleted", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
