"""Change date_joined,first and last name to mapped column

Revision ID: 349992158dd7
Revises: 7589b3275af5
Create Date: 2023-03-10 08:01:30.171356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "349992158dd7"
down_revision = "7589b3275af5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
