"""Add relationship between currency and country

Revision ID: 49044053cb73
Revises: 31bcde054202
Create Date: 2023-03-10 15:45:54.470288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "49044053cb73"
down_revision = "31bcde054202"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("currency", sa.Column("country_id", sa.String(), nullable=True))
    op.create_foreign_key(None, "currency", "country", ["country_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "currency", type_="foreignkey")
    op.drop_column("currency", "country_id")
    # ### end Alembic commands ###
