"""Overhaul UserRole model

Revision ID: 66e591c6c17d
Revises: 95c65e9f0cd5
Create Date: 2023-03-08 14:44:16.292936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "66e591c6c17d"
down_revision = "95c65e9f0cd5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("permissions", sa.Text(), nullable=True),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("userrole", sa.Column("role_id", sa.String()))
    op.create_foreign_key(
        None, "userrole", "role", ["role_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("userrole", "name")
    op.drop_column("userrole", "scope")
    op.drop_column("userrole", "permissions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "userrole",
        sa.Column("permissions", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "userrole", sa.Column("scope", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "userrole", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "userrole", type_="foreignkey")
    op.drop_column("userrole", "role_id")
    op.drop_table("role")
    # ### end Alembic commands ###
