"""Add relationship in country to currency

Revision ID: 7ccf1b18fc57
Revises: dc80cf21ddfe
Create Date: 2023-03-10 15:51:53.885057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7ccf1b18fc57"
down_revision = "dc80cf21ddfe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("currency_country_id_fkey", "currency", type_="foreignkey")
    op.drop_column("currency", "country_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "currency",
        sa.Column("country_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "currency_country_id_fkey", "currency", "country", ["country_id"], ["id"]
    )
    # ### end Alembic commands ###
