"""Modify models related to User to have cascade delete

Revision ID: 91728cc9c074
Revises: ed0230c69a38
Create Date: 2023-02-28 13:32:13.926299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91728cc9c074'
down_revision = 'ed0230c69a38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('authtoken_user_id_fkey', 'authtoken', type_='foreignkey')
    op.create_foreign_key(None, 'authtoken', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('userrole_user_id_fkey', 'userrole', type_='foreignkey')
    op.create_foreign_key(None, 'userrole', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userrole', type_='foreignkey')
    op.create_foreign_key('userrole_user_id_fkey', 'userrole', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'authtoken', type_='foreignkey')
    op.create_foreign_key('authtoken_user_id_fkey', 'authtoken', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
