"""Create user roles model

Revision ID: 91f0c89554bf
Revises: a92014f5dd9d
Create Date: 2023-02-22 22:17:35.400304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91f0c89554bf'
down_revision = 'a92014f5dd9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userrole',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('_permissions', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userrole')
    # ### end Alembic commands ###
