"""Update column to mapped_column

Revision ID: 95c65e9f0cd5
Revises: 3a173b30441a
Create Date: 2023-03-08 14:19:30.207647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "95c65e9f0cd5"
down_revision = "3a173b30441a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
