"""Fix possible relationship issue in BusinessPartner

Revision ID: b457c3be5051
Revises: 187e5d694a81
Create Date: 2023-03-15 00:26:04.305242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b457c3be5051"
down_revision = "187e5d694a81"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
