"""Upgrade Authtoken model to use mapped_column

Revision ID: c1ed7655af2f
Revises: 32c68bd854b8
Create Date: 2023-03-17 13:55:42.461549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c1ed7655af2f"
down_revision = "32c68bd854b8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
