"""Create column_property in Base model

Revision ID: c9de8d6da120
Revises: c1ed7655af2f
Create Date: 2023-03-17 15:31:23.246294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c9de8d6da120"
down_revision = "c1ed7655af2f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
