"""Email is nullable and change authtoken column names

Revision ID: daefc1309af9
Revises: 99f992db3864
Create Date: 2023-02-18 22:10:24.491196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import func

# revision identifiers, used by Alembic.
revision = 'daefc1309af9'
down_revision = '99f992db3864'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authtoken', sa.Column('access_token_expires_at', sa.DateTime(), nullable=False, server_default=func.now()))
    op.add_column('authtoken', sa.Column('refresh_token_expires_in', sa.Integer(), nullable=False, server_default=sa.text("0")))
    op.drop_column('authtoken', 'expires_at')
    op.drop_column('authtoken', 'expires_in')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authtoken', sa.Column('expires_in', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('authtoken', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('authtoken', 'refresh_token_expires_in')
    op.drop_column('authtoken', 'access_token_expires_at')
    # ### end Alembic commands ###
