"""Remove relationship in currency

Revision ID: dc80cf21ddfe
Revises: 65f8e1a0b852
Create Date: 2023-03-10 15:50:19.929190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dc80cf21ddfe"
down_revision = "65f8e1a0b852"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
