"""Change scope column type

Revision ID: e65ac8b12f76
Revises: c9de8d6da120
Create Date: 2023-03-19 09:14:49.939682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e65ac8b12f76"
down_revision = "c9de8d6da120"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("userrole", sa.Column("permissions", sa.Text(), nullable=True))
    op.drop_column("userrole", "scope")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "userrole",
        sa.Column(
            "scope",
            postgresql.ARRAY(sa.VARCHAR()),
            server_default=sa.text("'{}'::character varying[]"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("userrole", "permissions")
    # ### end Alembic commands ###
