"""Rename scope model

Revision ID: effb2e0d742d
Revises: e65ac8b12f76
Create Date: 2023-03-19 09:17:25.913639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "effb2e0d742d"
down_revision = "e65ac8b12f76"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("userrole", sa.Column("scope", sa.Text(), nullable=True))
    op.drop_column("userrole", "permissions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "userrole",
        sa.Column("permissions", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("userrole", "scope")
    # ### end Alembic commands ###
